# TODO Array for environments 
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kkk
  namespace: adn-kubrix
  labels:
    platform-engineer.cloud/creator: backstage-template
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: kubrix-project
  source:
    repoURL: https://github.com/phac008/kkk.git
    targetRevision: main
    path: helm/chart
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: kubrix-kkk
  syncPolicy:
    managedNamespaceMetadata:
      labels: 
        platform-engineer.cloud/kyverno: kubevirt-rolebinding
    automated: 
      prune: true
      selfHeal: true
      allowEmpty: true
    syncOptions:
    - CreateNamespace=true      
    retry:
      limit: 0 # number of failed sync attempt retries; unlimited number of attempts if less than 0
      backoff:
        duration: 5s # the amount to back off. Default unit is seconds, but could also be a duration (e.g. "2m", "1h")
        factor: 2 # a factor to multiply the base duration after each failed retry
        maxDuration: 10m # the maximum amount of time allowed for the backoff strategy

